# Generated by Django 4.1.5 on 2023-01-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jordan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('description', models.TextField(max_length=2000)),
                ('size38', models.BooleanField(verbose_name='Наличие размера')),
                ('size39', models.BooleanField(verbose_name='Наличие размера')),
                ('size40', models.BooleanField(verbose_name='Наличие размера')),
                ('size41', models.BooleanField(verbose_name='Наличие размера')),
                ('size42', models.BooleanField(verbose_name='Наличие размера')),
                ('size43', models.BooleanField(verbose_name='Наличие размера')),
                ('size44', models.BooleanField(verbose_name='Наличие размера')),
                ('size45', models.BooleanField(verbose_name='Наличие размера')),
                ('image', models.ImageField(blank=True, upload_to='jordan/%Y/%m/%d')),
            ],
        ),
    ]
