# Generated by Django 4.1.5 on 2023-01-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jordan',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='image',
            field=models.ImageField(blank=True, upload_to='myapp/static', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size38',
            field=models.BooleanField(verbose_name='38'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size39',
            field=models.BooleanField(verbose_name='39'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size40',
            field=models.BooleanField(verbose_name='40'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size41',
            field=models.BooleanField(verbose_name='41'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size42',
            field=models.BooleanField(verbose_name='42'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size43',
            field=models.BooleanField(verbose_name='43'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size44',
            field=models.BooleanField(verbose_name='44'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='size45',
            field=models.BooleanField(verbose_name='45'),
        ),
    ]
