# Generated by Django 4.1.5 on 2023-01-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakersite', '0002_alter_jordan_description_alter_jordan_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('size38', models.BooleanField(verbose_name='38')),
                ('size39', models.BooleanField(verbose_name='39')),
                ('size40', models.BooleanField(verbose_name='40')),
                ('size41', models.BooleanField(verbose_name='41')),
                ('size42', models.BooleanField(verbose_name='42')),
                ('size43', models.BooleanField(verbose_name='43')),
                ('size44', models.BooleanField(verbose_name='44')),
                ('size45', models.BooleanField(verbose_name='45')),
                ('image', models.ImageField(blank=True, upload_to='images/adidas', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='nike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('size38', models.BooleanField(verbose_name='38')),
                ('size39', models.BooleanField(verbose_name='39')),
                ('size40', models.BooleanField(verbose_name='40')),
                ('size41', models.BooleanField(verbose_name='41')),
                ('size42', models.BooleanField(verbose_name='42')),
                ('size43', models.BooleanField(verbose_name='43')),
                ('size44', models.BooleanField(verbose_name='44')),
                ('size45', models.BooleanField(verbose_name='45')),
                ('image', models.ImageField(blank=True, upload_to='images/nike', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='jordan',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/jordan', verbose_name='Изображение'),
        ),
    ]
