# Generated by Django 4.1.5 on 2023-01-13 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sneakersite', '0004_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adidas',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/adidas/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='jordan',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/jordan/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='nike',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/nike/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='cart_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneakerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakersite.nike')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
