# Generated by Django 4.1.5 on 2023-01-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakersite', '0005_alter_adidas_image_alter_jordan_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_model',
        ),
    ]
